# NAME: NginxUI
# DESCRIPTION: Nginx UI - Load Balancer Management
# ENABLED: true
# NOTE: Each node gets its own data directory to avoid contention
#       Cluster sync is handled by NginxUI's built-in cluster feature
# REQUIRES: docker node update --label-add loadbalancer=true <NODE>

services:
  LoadBalancer:
    image: uozi/nginx-ui:sha-4754ef3
    hostname: '{{.Node.Hostname}}'
    environment:
      TZ: UTC
      # Skip installation wizard
      NGINX_UI_NODE_SKIP_INSTALLATION: "true"
      # Node display name is hostname
      NGINX_UI_NODE_NAME: "{{.Node.Hostname}}"
      # Predefined admin user (change in production)
      NGINX_UI_PREDEFINED_USER_NAME: "admin"
      NGINX_UI_PREDEFINED_USER_PASSWORD: "admin"
      # Secrets (defaults - should be changed in production)
      NGINX_UI_NODE_SECRET: "dscotctl-default-node-secret"
      NGINX_UI_APP_JWT_SECRET: "dscotctl-default-jwt-secret"
      NGINX_UI_CRYPTO_SECRET: "dscotctl-default-crypto-secret"
    ports:
      - target: 9000
        published: 9000
        protocol: tcp
        mode: host
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      # Per-node directories to avoid write contention
      - /mnt/MicroCephFS/docker-swarm-0001/data/NginxUI/{{.Node.Hostname}}:/etc/nginx:rw
      - /mnt/MicroCephFS/docker-swarm-0001/data/NginxUI/{{.Node.Hostname}}/nginx-ui:/etc/nginx-ui:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - DOCKER-SWARM-CLUSTER-INTERNAL-COMMUNICATION
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os==linux
          - node.labels.loadbalancer==true
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: stop-first
      rollback_config:
        parallelism: 1
        delay: 10s

networks:
  DOCKER-SWARM-CLUSTER-INTERNAL-COMMUNICATION:
    external: true

