# NAME: Portainer
# DESCRIPTION: Portainer CE - Container management UI for Docker Swarm
# ENABLED: true
# NOTE: Portainer is accessed via NginxUI reverse proxy at /portainer/
#       Port 8000 (agent tunnel) is exposed via TCP stream on NginxUI

services:
  Portainer:
    image: portainer/portainer-ce:latest
    hostname: 'portainer-{{.Node.ID}}'
    command: -H tcp://tasks.PortainerAgent:9001 --tlsskipverify --base-url /portainer
    environment:
      PORTAINER_AGENT_ADDR: tasks.PortainerAgent
      LOG_LEVEL: INFO
    # No published ports - accessed via NginxUI reverse proxy
    # Port 9000 (HTTP) -> /portainer/ location in NginxUI
    # Port 8000 (agent tunnel) -> TCP stream in NginxUI
    volumes:
      - /mnt/MicroCephFS/docker-swarm-0001/data/Portainer:/data:rw
    networks:
      - INTERNAL
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.platform.os==linux
          - node.role==manager
      resources:
        limits:
          cpus: '8'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: stop-first
      rollback_config:
        parallelism: 1
        delay: 10s

networks:
  INTERNAL:
    name: DOCKER-SWARM-SERVICES-INTERNAL
    external: true
